### ISSUE TITLE
[BUG] Waydroid doesn't capture mouse properly?

### ISSUE THREAD

**Issue by Qrtrdane** [waydroid/waydroid#2073]
### Describe the bug

Note: Potential duplicate of https://github.com/waydroid/waydroid/issues/2006.

Running Waydroid in a non-wayland desktop environment via Weston, Cage, or a VM (with a wayland-native distro/DE) results in games that should capture mouse (for looking around in a 3D environment etc.) to not do so properly.

When windowed, the mouse cursor can freely leave the window (the movement continues to be read in this case, but naturally clicking a mouse button results in whatever happens to be beneath the cursor to act accordingly), and in both windowed and fullscreen modes the looking-around movement halts when the cursor hits the edge of the screen, severely limiting the available range of motion.

I have tested this in the following games, all exhibiting the same behaviour:
- Destiny: Rising, installed via Google Play Store (https://play.google.com/store/apps/details?id=com.netease.g108na)
- Red Handed, running in a browser in Waydroid (https://badpiggy.itch.io/red-handed)

### Waydroid version

1.5.4

### Device

Linux Desktop

### Operating System

LMDE 6 (faye) x86_64

### Kernel version

6.1.0-40-amd64

### Desktop Environment

Cinnamon 6.4.8

### GPU

AMD Radeon RX 6750 XT

### Logs

[waydroid.cfg.txt](https://github.com/user-attachments/files/22635182/waydroid.cfg.txt)
[waydroid.prop.txt](https://github.com/user-attachments/files/22635180/waydroid.prop.txt)
[waydroid_base.prop.txt](https://github.com/user-attachments/files/22635179/waydroid_base.prop.txt)
[waydroid.log](https://github.com/user-attachments/files/22635181/waydroid.log)
[logcat.txt](https://github.com/user-attachments/files/22635192/logcat.txt)
[dmesg.txt](https://github.com/user-attachments/files/22635193/dmesg.txt)

**Comment by Qrtrdane** [comment]
That particular version of cage throws this error when I attempt to run it:

/lib/x86_64-linux-gnu/libc.so.6: version `GLIBC_2.38' not found (required by ./cage-waydroid-helper_202509201042_amd64)

I also tried the two oldest cage-waydroid-helper releases - 202509060852 and 0.0.1 - of which only the latter actually functioned (former giving the same error as above).

For some reason, though, I can't seem to get waydroid-helper to actually start the session unless I run the helper itself in weston/cage/etc.

I also noticed the helper's option section for cage having much more options (e.g. refresh rate) than I get with "cage --help", presumably a version difference?

Additionally, when testing both the waydroid-helper's cage and the one found via my distro's package manager, I noticed that the former maps input devices x11-pointer and x11-touch to output device x11-1 (could the additional touch input cause issues?), whereas the latter just spews a long list of "Basic output test failed for x11-1" and not much else (while still functioning as well as it does).

**Comment by ayasa520** [comment]
@Qrtrdane  I've released a new build: https://github.com/waydroid-helper/cage/releases/download/legacy/cage_amd64 . Please try it and tell me if it works.

To make 'mouse capture' work, you need to follow the key mapping instructions in https://github.com/waydroid-helper/waydroid-helper/blob/main/docs/KEY_MAPPING.md
. This might not match your expectations, so I removed my previous comment.

https://github.com/user-attachments/assets/c77cb0a6-e8d7-4d69-bf77-6786d7cdb938

**Comment by Qrtrdane** [comment]
> [@Qrtrdane](https://github.com/Qrtrdane) I've released a new build: https://github.com/waydroid-helper/cage/releases/download/legacy/cage_amd64 . Please try it and tell me if it works.

Attempting to launch anything with that build results in the following errors:
```
amdgpu: amdgpu_cs_ctx_create2 failed. (-13)
00:00:00.032 [types/wlr_shm.c:536] wl_global_create failed
00:00:00.033 [../cage.c:452] Unable to create the wlroots compositor
cage_amd64: backend/x11/backend.c:269: get_x11_backend_from_backend: Assertion `wlr_backend_is_x11(wlr_backend)' failed.
Aborted (core dumped)
```
> To make 'mouse capture' work, you need to follow the key mapping instructions in https://github.com/waydroid-helper/waydroid-helper/blob/main/docs/KEY_MAPPING.md . This might not match your expectations, so I removed my previous comment.
> output.mp4

That is indeed very different from what I'm after, as the game(s) in question have proper mouse support (so there shouldn't be any need for a mouse-to-touch translation layer).
Also I can't even seem to open the key mapping window, regardless of whether I'm running the helper natively or via weston/cage.

**Comment by Qrtrdane** [comment]
Update: Installed KDE Plasma desktop environment, and Waydroid appears to function properly with it. Desktop manager's still the same as before (lightdm).
Also have been talking with someone with a similar problem on Destiny: Rising's discord - despite their setup having a wayland-native DE (cosmic, on gdm). They said they're going to try KDE to see if that helps, and if it doesn't (and they have time), replacing gdm with sddm.

**Comment by Qrtrdane** [comment]
Further update, the aforementioned person has now tested GNOME, COSMIC, and KDE Plasma on GDE - and only on KDE Plasma did the mouse capture function properly.
