### ISSUE TITLE
Binder error on Fedora XanMod

### ISSUE THREAD

**Issue by VodnikAngus** [waydroid/waydroid#208]
Error starting waydroid on Fedora 35

```
$ systemctl start waydroid-container.service
× waydroid-container.service - Waydroid Container
     Loaded: loaded (/usr/lib/systemd/system/waydroid-container.service; disabled; vendor preset: disabled)
     Active: failed (Result: exit-code) since Tue 2021-11-02 22:52:51 CET; 6min ago
    Process: 3863 ExecStart=/usr/bin/waydroid container start (code=exited, status=1/FAILURE)
    Process: 3868 ExecStopPost=/usr/bin/waydroid session stop (code=exited, status=0/SUCCESS)
   Main PID: 3863 (code=exited, status=1/FAILURE)
        CPU: 131ms

Nov 02 22:52:50 desktop systemd[1]: Started Waydroid Container.
Nov 02 22:52:50 desktop waydroid[3863]: [22:52:50] ERROR: [Errno 13] Permission denied: '/dev/binderfs/binder-control'
Nov 02 22:52:50 desktop waydroid[3863]: [22:52:50] See also: <https://github.com/waydroid>
Nov 02 22:52:50 desktop waydroid[3863]: Run 'waydroid log' for details.
Nov 02 22:52:50 desktop systemd[1]: waydroid-container.service: Main process exited, code=exited, status=1/FAILURE
Nov 02 22:52:51 desktop waydroid[3868]: [22:52:51] WayDroid session is not started
Nov 02 22:52:51 desktop systemd[1]: waydroid-container.service: Failed with result 'exit-code'.
```

Log:
```
(004900) [22:59:36] % mkdir -p /dev/binderfs
(004900) [22:59:36] % mount -t binder binder /dev/binderfs
(004900) [22:59:36] ERROR: [Errno 13] Permission denied: '/dev/binderfs/binder-control'
(004900) [22:59:36] See also: <https://github.com/waydroid>
(004900) [22:59:36] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 69, in main
    actions.container_manager.start(args)
  File "/usr/lib/waydroid/tools/actions/container_manager.py", line 94, in start
    if helpers.drivers.probeBinderDriver(args) != 0:
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 105, in probeBinderDriver
    allocBinderNodes(args, binder_dev_nodes)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 59, in allocBinderNodes
    binderctrlfd = open('/dev/binderfs/binder-control','rb')
PermissionError: [Errno 13] Permission denied: '/dev/binderfs/binder-control'

(004905) [22:59:36] WayDroid session is not started
```

System infromation:
Fedora 35
XanMod kernel 5.14.15 with ``pci=1`` flag
Ryzen 3600x
16gb RAM
All packages up to date

**Comment by tdrkDev** [comment]
What fixed that? I have the same environment, except hardware.

**Comment by VodnikAngus** [comment]
I didn't get the Waydroid runnin I just shuffled many error messages and stopped trying after that...

I think this one was fixed by changing a config file to use waydroid-binder instead of just binder but I could be wrong

**Comment by tdrkDev** [comment]
> I didn't get the Waydroid runnin I just shuffled many error messages and stopped trying after that...
> 
> I think this one was fixed by changing a config file to use waydroid-binder instead of just binder but I could be wrong

So I've fixed that. You need to change waydroid config under /var to use /dev/anbox-XXXbinder. Also you need to set permissive SELinux.

**Comment by tr1p0p** [comment]
Why close the issues when it's not fixed ? It's could be useful for others.

**Comment by offlinehacker** [comment]
This is how I managed to get it working with selinux enabled: https://discussion.fedoraproject.org/t/ashmem-and-binderfs-copr-for-anbox-and-waydroid/36492#workarounds-for-selinux-on-fedora-35-2

**Comment by TeHMoroS** [comment]
Building on top of offlinehacker's answer I was able to isolate a single line change in Waydroid to get this running.

In tools/helpers/drivers.py you can change the line below (line 103 in my case):
```python
command = ["mount", "-t", "binder", "binder", "/dev/binderfs"]
```
to
```python
command = ["mount", "-t", "binder", "-o", "context=system_u:object_r:device_t:s0", "binder", "/dev/binderfs"]
```

That being said, the above is only to get this running. It should probably have some additional logic to "detect" whether the `context` option should be applied or not (check if SELinux policies enforced and react accordingly).

I feel like this should still be an open issue, as the bug is there, on systems that enforce SELinux policies.
