### ISSUE TITLE
[BUG] Android Cursor Lock Does not Lock the cursor and Escapes Outside

### ISSUE THREAD

**Issue by caffeinepyroxene** [waydroid/waydroid#2130]
### Describe the bug

The cursor does not stay locked in games which capture mouse/cursor in allow you to move the camera and play the game. This issue has been discussed here before: https://github.com/waydroid/waydroid/issues/2006 but it was marked as complete. I updated my waydroid image to the latest in order to test, but the issue is still there. 
I've even tried to reset all user data, and the issue still persists. In the closed bug report, I mentioned downgrading the waydroid image to date: 20250705 from sourceforge https://github.com/waydroid/waydroid/issues/2006#issuecomment-3278546075 and this workaround still works.
The issue is only with newer builds of waydroid images, and hopefully it gets fixed, if possible? I attached all logs I had.

Some Examples
Main Example: Minecraft
Other Games: Free Fire MAX (has a dedicated cursor lock key in game settings)

https://github.com/user-attachments/assets/a9fda588-2e2b-4fa2-af09-9418b893f968

### Waydroid version

1.5.4-4

### Device

Linux Desktop

### Operating System

Manjaro

### Kernel version

Linux 6.17.8-2-MANJARO

### Desktop Environment

Gnome 49

### GPU

Intel® Iris® Xe Graphics (ADL GT2)

### Logs

/var/lib/waydroid/waydroid.cfg - 
/var/lib/waydroid/waydroid.prop - 
/var/lib/waydroid/waydroid_base.prop
/var/lib/waydroid/waydroid.log - 

[waydroid.prop.txt](https://github.com/user-attachments/files/23687238/waydroid.prop.txt)
[waydroid.cfg.txt](https://github.com/user-attachments/files/23687239/waydroid.cfg.txt)
[waydroid_base.prop.txt](https://github.com/user-attachments/files/23687240/waydroid_base.prop.txt)
[waydroid.log](https://github.com/user-attachments/files/23687224/waydroid.log)

`sudo waydroid shell -- logcat -d | tee logcat.txt`

[logcat.txt](https://github.com/user-attachments/files/23687243/logcat.txt)

`sudo dmesg | tee dmesg.txt`

[dmesg.txt](https://github.com/user-attachments/files/23687245/dmesg.txt)

**Comment by caffeinepx** [comment]
This is what the "expected behavior" is like after downgrading to an image near 20250705. The cursor stays locked into the game window and does not escape

https://github.com/user-attachments/assets/8da92fa5-8dd4-4da1-8bd7-bf910c053ccb

**Comment by aleasto** [comment]
This was already fixed, but an update is not available yet due to a build infrastructure failure

**Comment by djgallentine45-source** [comment]
I am still experiencing this exact issue, which is worse when using multiple monitors.

**Comment by caffeinepx** [comment]
> I am still experiencing this exact issue, which is worse when using multiple monitors.

current solution is only to downgrade to an older image version, im using build 20250705 from sourceforge and it works fine without this issue

other solution is to wait for new builds to be released

**Comment by djgallentine45-source** [comment]
Mine might be more DE and Destiny Rising related. I am going to test on KDE Plasma as others have stated that may work. Not sure why it only seems to work in KDE Plasma. If it does, will open separate ticket for that.

**Comment by djgallentine45-source** [comment]
KDE Plasma does work on most current version of Waydroid, at least with Destiny Rising.

**Comment by ghost** [comment]
What I did was set the width and height props to exactly match my screen resolution, then added an “open fullscreen" rule for waydroid in my compositor. After that, I just run "waydroid show-full-ui" and it fits perfectly.
