### ISSUE TITLE
[Ubuntu 21.10] Binder node "binder" for waydroid not found

### ISSUE THREAD

**Issue by Doomsdayrs** [waydroid/waydroid#47]
On Ubuntu 21.10, waydroid still fails to find binder.

I am not too experienced with kernel modules, but I posted the logs with verbose here

[ubuntu-imprish-crash.txt](https://github.com/waydroid/waydroid/files/7155679/ubuntu-imprish-crash.txt)

**Comment by Doomsdayrs** [comment]
5.13.0.-14-lowlatency does not work either

**Comment by earboxer** [comment]
Hi, same issue (but on hirsute (21.04) `5.11.0-34-generic`).

`linux_binder` (and `ashmem_linux`) are loaded (verified with `lsmod | grep -e ashmem_linux -e binder_linux`).

In `/dev`, I have `binder-control` and `binderfs` (but none of the drivers listed in `tools/helpers/drivers.py`)

Presumably we need a 5.14 kernel or greater? It might be nice to have this in the documentation.

**Comment by Sparticuz** [comment]
Similar, but for Arch. I've got (only) `/dev/binderfs/binder-control`. I am running 5.14, and hitting https://github.com/waydroid/waydroid/blob/bullseye/tools/helpers/drivers.py#L104

**Comment by johodh** [comment]
I have the same issue, modules loaded but binder node not found. Running Arch based EndeavourOS

**Comment by teppyboy** [comment]
So Waydroid isn't detecting binderfs (which is the one people in this issue using)
There's a workaround here https://aur.archlinux.org/packages/waydroid/#comment-827918
But well it would be nice if Waydroid add binderfs support

**Comment by mizzunet** [comment]
@teppyboy Would you please tell, which file this line appended to?
```
binder.devices=binder,hwbinder,vndbinder,anbox-binder,anbox-hwbinder,anbox-vndbinder
```
where is `boot cmdline` file located?

BTW, the kernel is `Linux arch 5.15.2-arch1-1`

**Comment by teppyboy** [comment]
/etc/default/grub in the GRUB_CMDLINE_LINUX_DEFAULT and btw this **will
not** work in default kernel, you need to use `linux-zen` or the tkg ones.

Vào 21:28, Th 2, 22 thg 11, 2021 Missu ***@***.***> đã viết:

**Comment by youling257** [comment]
(000588) [23:30:38] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
(000588) [23:30:38] % mkdir -p /dev/binderfs
(000588) [23:30:38] % mount -t binder binder /dev/binderfs
(000588) [23:30:38] % ln -s /dev/binderfs/features /dev/binderfs/anbox-hwbinder /dev/binderfs/anbox-vndbinder /dev/binderfs/anbox-binder /dev/binderfs/binder-control /dev/
(000588) [23:30:38] % modprobe ashmem_linux

I edit /lib/waydroid/tools/helpers/drivers.py ,   
            command = ["modprobe", "binder_linux",
                       "devices=binder,hwbinder,vndbinder,anbox-binder,anbox-hwbinder,anbox-vndbinder".format(devices)]

**Comment by erfanoabdi** [comment]
fixed long time ago https://github.com/waydroid/waydroid/commit/20d3c5e2cf4fd91e35205a1abfae24456c05fc2e

**Comment by amithm7** [comment]
Still having this problem, `waydroid log`:

```console
(827263) [12:30:29] % modprobe binder_linux devices="anbox-binder,anbox-vndbinder,anbox-hwbinder"
(827263) [12:30:29] ERROR: Binder node "binder" for waydroid not found
(827263) [12:30:29] See also: <https://github.com/waydroid>
(827263) [12:30:29] Traceback (most recent call last):
  File "/usr/lib/waydroid/tools/__init__.py", line 64, in main
    actions.init(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 110, in init
    setup_config(args)
  File "/usr/lib/waydroid/tools/actions/initializer.py", line 97, in setup_config
    helpers.drivers.setupBinderNodes(args)
  File "/usr/lib/waydroid/tools/helpers/drivers.py", line 134, in setupBinderNodes
    raise OSError('Binder node "binder" for waydroid not found')
OSError: Binder node "binder" for waydroid not found
```

On debian bookworm / testing.
