### ISSUE TITLE
What are the new Lineage 18.1 Kernel config options that weren't needed with 17.1?

### ISSUE THREAD

**Issue by HanoJing** [waydroid/waydroid#738]
**Describe the bug**
Not a bug, a question: Since Lineage 18.1 images, new Kernel config options are needed for Waydroid to work. 

**General information (please complete the following information):**
Waydroid tools Version: 1.3.4
Waydroid Images Version: lineage-18.1-20230204-GAPPS-waydroid_arm64-system

**Desktop (please complete the following information):**
OS: Void Linux ARM64
Motherboard: SolidRun HoneyComb LX2K
CPU: NXP LayerScape LX2160A Cortex-A72 ARM
GPU: AMD Radeon RX580 XFX
Kernel version: 5.19.7 (SolidRun Vendor Kernel with a custom kernel config)
Host mesa version: 22.2.4
Desktop: Xorg, DWM (Suckless Dynamic Window Manager)

**Additional context**
Referencing what was done in #402, 15 hours is a real marathon. The devs might know what options are exactly needed. 
The Lineage 18.1 images work with the Void Linux distro-kernel.

**Logs (please upload as file)**
Prop file: [waydroid.log](https://github.com/waydroid/waydroid/files/10608291/waydroid.log)
Output of `waydroid log`: [waydroid-log.log](https://github.com/waydroid/waydroid/files/10608274/waydroid-log.log)
*Full* (not partially) Output of `waydroid logcat`: WayDroid container is STOPPED

dmesg: [dmesg.log](https://github.com/waydroid/waydroid/files/10608316/dmesg.log)

**Comment by HanoJing** [comment]
Fixed! 

Definitely make sure to run `lxc-checkconfig`, look and see if it says enabled on (almost) everything (I don't use systemd, so there is: `Cgroup v1 systemd controller: missing`.

`Cgroup v1 mount points` are important.

I have set the following: 

```
/sys/fs/cgroup/cpuset
/sys/fs/cgroup/cpu
/sys/fs/cgroup/cpuacct
/sys/fs/cgroup/blkio
/sys/fs/cgroup/memory
/sys/fs/cgroup/devices
/sys/fs/cgroup/freezer
/sys/fs/cgroup/perf_event
/sys/fs/cgroup/pids
/sys/fs/cgroup/rdma
/sys/fs/cgroup/misc
/sys/fs/cgroup/elogind
```

to enable further CGROUP controllers, go to CONFIG_CGROUPS in your kernel config and add controllers.

**Comment by Flashwalker** [comment]
it still fails to start at first launch out of the box.

On the first startup, after loading VANILA, I saw the bootable animated logo and then it died.

Now all i can see is:
<details><summary>Details</summary>
<p>

```
$ waydroid first-launch
[18:18:37] Waiting for binder Service Manager...
[18:19:37] Service Manager never appeared
[18:19:37] Failed to access IPlatform service
```

```
$ systemctl status waydroid-container.service
● waydroid-container.service - Waydroid Container
     Loaded: loaded (/usr/lib/systemd/system/waydroid-container.service; enabled; preset: enabled)
     Active: active (running) since Fri 2025-01-10 17:51:39 +07; 40min ago
   Main PID: 64683 (waydroid)
      Tasks: 6 (limit: 37862)
     Memory: 2.2G (peak: 2.4G)
        CPU: 30.306s
     CGroup: /system.slice/waydroid-container.service
             ├─64683 /usr/bin/python3 /usr/bin/waydroid -w container start
             └─65617 dnsmasq --conf-file=/dev/null -u dnsmasq --strict-order --bind-interfaces --pid-file=/run/waydroid-lxc/dnsmasq.pid --listen-address 192.168.240.1 --dhcp-range>

янв 10 17:57:44 redtop waydroid[65394]: [17:57:44] Extracting to /var/lib/waydroid/images
янв 10 17:58:13 redtop dnsmasq[65617]: started, version 2.90 cachesize 150
янв 10 17:58:13 redtop dnsmasq[65617]: compile time options: IPv6 GNU-getopt DBus no-UBus i18n IDN2 DHCP DHCPv6 no-Lua TFTP conntrack ipset nftset auth cryptohash DNSSEC loop-dete>
янв 10 17:58:13 redtop dnsmasq-dhcp[65617]: DHCP, IP range 192.168.240.2 -- 192.168.240.254, lease time 1h
янв 10 17:58:13 redtop dnsmasq-dhcp[65617]: DHCP, sockets bound exclusively to interface waydroid0
янв 10 17:58:13 redtop dnsmasq[65617]: reading /etc/resolv.conf
янв 10 17:58:13 redtop dnsmasq[65617]: using nameserver 10.0.10.2#53
янв 10 17:58:13 redtop dnsmasq[65617]: using nameserver 10.0.10.3#53
янв 10 17:58:13 redtop dnsmasq[65617]: using nameserver 192.168.0.1#53
янв 10 17:58:13 redtop dnsmasq[65617]: read /etc/hosts - 7 names
```

```
$ lxc-checkconfig
LXC version 5.0.3
Kernel configuration not found at /proc/config.gz; searching...
Kernel configuration found at /boot/config-6.12.8-x64v3-xanmod1

--- Namespaces ---
Namespaces: enabled
Utsname namespace: enabled
Ipc namespace: enabled
Pid namespace: enabled
User namespace: enabled
newuidmap is not installed
newgidmap is not installed
Network namespace: enabled

--- Control groups ---
Cgroups: enabled
Cgroup namespace: enabled
Cgroup v1 mount points: 
Cgroup v2 mount points: 
 - /sys/fs/cgroup
Cgroup device: enabled
Cgroup sched: enabled
Cgroup cpu account: enabled
Cgroup memory controller: enabled
Cgroup cpuset: enabled

--- Misc ---
Veth pair device: enabled, loaded
Macvlan: enabled, not loaded
Vlan: enabled, not loaded
Bridges: enabled, loaded
Advanced netfilter: enabled, loaded
CONFIG_IP_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_IP6_NF_TARGET_MASQUERADE: enabled, not loaded
CONFIG_NETFILTER_XT_TARGET_CHECKSUM: enabled, loaded
CONFIG_NETFILTER_XT_MATCH_COMMENT: enabled, loaded
FUSE (for use with lxcfs): enabled, not loaded

--- Checkpoint/Restore ---
checkpoint restore: enabled
CONFIG_FHANDLE: enabled
CONFIG_EVENTFD: enabled
CONFIG_EPOLL: enabled
CONFIG_UNIX_DIAG: enabled
CONFIG_INET_DIAG: enabled
CONFIG_PACKET_DIAG: enabled
CONFIG_NETLINK_DIAG: enabled
File capabilities: enabled

Note : Before booting a new kernel, you can check its configuration
usage : CONFIG=/path/to/config /usr/bin/lxc-checkconfig
```

```
$ waydroid status
Session:	RUNNING
Container:	STOPPED
Vendor type:	MAINLINE
IP address:	UNKNOWN
Session user:	user(1000)
Wayland display:	wayland-0
```

</p>
</details>
